### ISSUE TITLE
Filtering orders doesn't work

### ISSUE THREAD

**Issue by hadwao** [LinkerCloud/linker-api-client#13]
Filters are igrnored durign order search. Issue can be fixed in file:
vendor/linker/api-client/src/Linker/Api/Client/HttpApiClient.php

Change
`        $endpoint = $this->endpoint . '/orders?limit=' . $limit .
            '&offset=' . $offset . '&sortCol=' . $sortColumn . '&sortDir=' . $sortDir;`

to:
`        $endpoint = $this->endpoint . '/orders?limit=' . $limit .
            '&offset=' . $offset . '&sortCol=' . $sortColumn . '&sortDir=' . $sortDir . $query;`

**Comment by hrba** [comment]
Issue should be fixed by 1915c60
